
applications:
  django-app:
    namespace: default
    source:
      repoURL: ""  
      path: ""     
      targetRevision: HEAD
repositories:
  - name: django-helm-chart
    url: https://github.com/SerAnatolii/my-microservice-project/tree/main/charts